### ISSUE TITLE
无法打开首页

### ISSUE THREAD

**Issue by HaloCsidez** [hooozen/hexo-theme-tranquility#12]
您好，我按照顺序部署了这个主题，但是无法打开首页，我该如何解决？

报错如下：
```
Unhandled rejection Template render error: (/root/blog/themes/tranquility/layout/index.njk)
  Template render error: (/root/blog/themes/tranquility/layout/index.njk) [Line 71, Column 31]
  Template render error: (/root/blog/themes/tranquility/layout/index.njk) [Line 1, Column 3]
  Template render error: (/root/blog/themes/tranquility/layout/index.njk) [Line 8, Column 3]
  Template render error: (/root/blog/themes/tranquility/layout/index.njk) [Line 83, Column 3]
  Template render error: (/root/blog/themes/tranquility/layout/index.njk)
  Template render error: (/root/blog/themes/tranquility/layout/_partials/scripts/HeartCurve.njk)
  Template render error: (/root/blog/themes/tranquility/layout/index.njk)
  Error: template not found: _partials/scripts/TimeLine.njk
    at Object._prettifyError (/root/blog/node_modules/nunjucks/src/lib.js:36:11)
    at /root/blog/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/root/blog/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:34:3)
    at Template.render (/root/blog/node_modules/nunjucks/src/environment.js:552:10)
    at /root/blog/node_modules/hexo/lib/plugins/renderer/nunjucks.js:67:37
    at _View._compiled (/root/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/root/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /root/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/root/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /root/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/root/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by HaloCsidez** [comment]
然而，我在相关目录下找到了这个TimeLine.njk文件
```
root@C20230320134123:~/blog/themes/tranquility/layout/_partials/scripts# ll
total 16
drwxr-xr-x 2 root root 4096 Apr  5 10:29 ./
drwxr-xr-x 5 root root 4096 Apr  5 10:29 ../
-rw-r--r-- 1 root root 3145 Apr  5 10:29 HeartCurve.njk
-rw-r--r-- 1 root root 1785 Apr  5 10:29 Timeline.njk
```

**Comment by HaloCsidez** [comment]
另外服务器上的Node版本为v18.15.0，npm版本为9.5.0

**Comment by hooozen** [comment]
这种情况我也很难看出具体的原因，不过你可以检查下你的 hexo 版本，看看使用 6.3.0 版本是否有效。

**Comment by imxiaocheng** [comment]
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/65651703/2d8c2af0-7bac-474c-9d5d-ba14e8ab8eb9)

**Comment by imxiaocheng** [comment]
这个问题怎么解决

**Comment by imxiaocheng** [comment]
INFO  Validating config
ERROR {
  err: Error: Cannot find module 'node:buffer'
  Require stack:
  - F:\blog\xcblog\themes\tranquility\scripts\generator\font.js
  - F:\blog\xcblog\themes\tranquility\scripts\index.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
      at Function.Module._load (internal/modules/cjs/loader.js:745:27)
      at Module.require (internal/modules/cjs/loader.js:961:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (F:\blog\xcblog\themes\tranquility\scripts\generator\font.js:4:20)
      at Module._compile (internal/modules/cjs/loader.js:1072:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
      at Module.load (internal/modules/cjs/loader.js:937:32)
      at Function.Module._load (internal/modules/cjs/loader.js:778:12)
      at Module.require (internal/modules/cjs/loader.js:961:19)
      at req (F:\blog\xcblog\node_modules\hexo\lib\hexo\index.js:292:23)
      at F:\blog\xcblog\themes\tranquility\scripts\index.js:2:1
      at F:\blog\xcblog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (F:\blog\xcblog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:15:14) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'F:\\blog\\xcblog\\themes\\tranquility\\scripts\\generator\\font.js',
      'F:\\blog\\xcblog\\themes\\tranquility\\scripts\\index.js'
    ]
  }
} Script load failed: %s themes\tranquility\scripts\index.js
ERROR {
  err: Error: Cannot find module 'node:buffer'
  Require stack:
  - F:\blog\xcblog\themes\tranquility\scripts\generator\font.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
      at Function.Module._load (internal/modules/cjs/loader.js:745:27)
      at Module.require (internal/modules/cjs/loader.js:961:19)
      at req (F:\blog\xcblog\node_modules\hexo\lib\hexo\index.js:292:23)
      at F:\blog\xcblog\themes\tranquility\scripts\generator\font.js:4:20
      at F:\blog\xcblog\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (F:\blog\xcblog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (F:\blog\xcblog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (F:\blog\xcblog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:464:21) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'F:\\blog\\xcblog\\themes\\tranquility\\scripts\\generator\\font.js'
    ]
  }
} Script load failed: %s themes\tranquility\scripts\generator\font.js
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

**Comment by hooozen** [comment]
@imxiaocheng 你的node版本是多少，更新一下node版本试试

**Comment by imxiaocheng** [comment]
没有
&nbsp;


时公城
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 晚上8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hooozen/hexo-theme-tranquility] 无法打开首页 (Issue #12)





 
@hooozen @HaloCsidez 您好，我也在使用博主的主题时遇到了上面的问题，请问这个问题解决了吗？

**Comment by Laicize** [comment]
@hooozen 博主，之前的问题通过把node20版本降到16似乎解决了，现在本地打开首页，是空白页，主题的yaml至打开了子页功能，其他默认。这是什么原因？f12查看好多内容没加载显示出来
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/42798006/ffebcc15-13c1-49c6-9517-3666556f57a6)

**Comment by hooozen** [comment]
你好，我关注到这个问题多出在linux系统中.  方便的话你可以先采用windows和macOS部署博客.  后面我就会使用linux系统定位问题.

**Comment by hooozen** [comment]
@Laicize @HaloCsidez 已修复Linux下无法运行的问题，请查看最新版本.

**Comment by hooozen** [comment]
> 这个问题怎么解决



> @imxiaocheng 你的node版本是多少，更新一下node版本试试

你的问题是由于 node 版本过低导致的
