### ISSUE TITLE
您好，在启动服务时一直报错，试了好多次没有解决，报错信息如下，能否麻烦您指导一下

### ISSUE THREAD

**Issue by Lixiaojun-lab** [hooozen/hexo-theme-tranquility#26]
INFO  Validating config
ERROR Script load failed: themes/tranquility/scripts/helper/fontawesome.js
Error: Cannot find module '@fortawesome/fontawesome-svg-core'
Require stack:
- /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (/Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:1:112
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
INFO  Start processing
Extract subfont:  ,“”一七三下不丝个了于余光入关内分剑半发口吐君唐啸堂天如存宁就己悲成明暮月朝比气海涯白的盛知绣肠致若见豪远邻酒酿镜雪青静高
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'enable')
    at Hexo.cvGenerator (/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/generator/cv.js:12:18)
    at Hexo.tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:407:22
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/map.js:68:38)
    at PromiseArray._iterate (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by hooozen** [comment]
您好，这是由于最新版本新增了简历功能，而你的主题配置文件未配置相关字段造成的。

请在你的主题配置文件中新增简历相关的 `cv` 字段，如果不需要该功能请仅配置 `cv.enable` 为 `false` 即可，例如

```yml
...
cv:
    enable: false
...
```

如果需要启用该功能，请查看最新的版本说明：https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.3.2

**Comment by Lixiaojun-lab** [comment]
好的，谢谢哥！

**Comment by Lixiaojun-lab** [comment]
哥，我在部署github环节中，遇到以下问题，能否麻烦您再看看
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % hexo g -d

INFO  Validating config
ERROR Script load failed: themes/tranquility/scripts/helper/fontawesome.js
Error: Cannot find module '@fortawesome/fontawesome-svg-core'
Require stack:
- /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (/Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:1:112
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
INFO  Start processing
Extract subfont:  ,aefls“”一七三下不丝个了于余光入关内分剑半发口吐君唐啸堂天如存宁就己悲成明暮月朝比气海涯白的盛知绣肠致若见豪远邻酒酿镜雪青静高
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
INFO  Files loaded in 228 ms
INFO  Generated: font/bold.ttf
INFO  Generated: font/regular.ttf
INFO  2 files generated in 24 ms
ERROR Deployer not found: git

就是这个模块：fortawesome/fontawesome-svg-core，也一直装不上

**Comment by hooozen** [comment]
不好意思，这里文档中出现了笔误，请尝试安装 fontawesome/...
非常感谢提出的问题，后续会更新文档和说明

**Comment by Lixiaojun-lab** [comment]
安装命令是npm install fontawesome/...吗哥

**Comment by hooozen** [comment]
我刚刚检查了一下，原文档应该是正确的，
请你再次尝试以下命令：
```
npm install @fortawesome/fontawesome-svg-core  --save
```

**Comment by Lixiaojun-lab** [comment]
好的哥，我再试试

**Comment by Lixiaojun-lab** [comment]
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % npm install @fortawesome/fontawesome-svg-core  --save
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /Users/lixiaojun/SuperLee-blog/node_modules/@fortawesome
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/Users/lixiaojun/SuperLee-blog/node_modules/@fortawesome'
npm ERR!  [Error: EACCES: permission denied, mkdir '/Users/lixiaojun/SuperLee-blog/node_modules/@fortawesome'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/lixiaojun/SuperLee-blog/node_modules/@fortawesome'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/lixiaojun/.npm/_logs/2023-09-12T03_27_41_537Z-debug-0.log
还是报错，不知道啥情况

**Comment by hooozen** [comment]
看报错提示应该是权限不足，尝试再命令前添加 `sudo` 指令，然后按提示输入电脑密码进行安装

**Comment by Lixiaojun-lab** [comment]
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % sudo npm install @fortawesome/fontawesome-svg-core  --save


up to date, audited 243 packages in 740ms

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % 
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % hexo g -d                                                 

INFO  Validating config
install icon fail: Error: Cannot find module '@fortawesome/free-solid-svg-icons'
Require stack:
- /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (/Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:14:33
    at tryInstall (/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:5:17)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:14:1
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js'
  ]
}
install icon fail: Error: Cannot find module '@fortawesome/free-regular-svg-icons'
Require stack:
- /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (/Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:15:33
    at tryInstall (/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:5:17)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:15:1
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js'
  ]
}
install icon fail: Error: Cannot find module '@fortawesome/free-brands-svg-icons'
Require stack:
- /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (/Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:292:23)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:16:33
    at tryInstall (/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:5:17)
    at /Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js:16:1
    at /Users/lixiaojun/SuperLee-blog/node_modules/hexo/lib/hexo/index.js:305:14
    at tryCatcher (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/lixiaojun/SuperLee-blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lixiaojun/SuperLee-blog/themes/tranquility/scripts/helper/fontawesome.js'
  ]
}
INFO  Start processing
Extract subfont:  ,aefls“”一七三下不丝个了于余光入关内分剑半发口吐君唐啸堂天如存宁就己悲成明暮月朝比气海涯白的盛知绣肠致若见豪远邻酒酿镜雪青静高
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
INFO  Files loaded in 241 ms
INFO  Generated: font/regular.ttf
INFO  Generated: font/bold.ttf
INFO  2 files generated in 25 ms
ERROR Deployer not found: git
(base) lixiaojun@lixiaojundeMacbookdeMacBook-Pro SuperLee-blog % npm install hexo-deployer-git --save                      

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /Users/lixiaojun/SuperLee-blog/node_modules/hexo-deployer-git
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/Users/lixiaojun/SuperLee-blog/node_modules/hexo-deployer-git'
npm ERR!  [Error: EACCES: permission denied, mkdir '/Users/lixiaojun/SuperLee-blog/node_modules/hexo-deployer-git'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/lixiaojun/SuperLee-blog/node_modules/hexo-deployer-git'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/lixiaojun/.npm/_logs/2023-09-12T03_33_33_788Z-debug-0.log
都试过了哥，我在想是不是node.js安装有问题，我是在官网上下载的安装包，是不是要通过命令行安装

**Comment by hooozen** [comment]
根据报错，你应该还是依赖没有安装完整，请查看[更新说明](https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.3.2)，安装以下依赖：

```
npm install @fortawesome/fontawesome-svg-core --save
npm install @fortawesome/free-solid-svg-icons --save
npm install @fortawesome/free-regular-svg-icons --save
npm install @fortawesome/free-brands-svg-icons --save
```

并查看[安装说明](https://github.com/hooozen/hexo-theme-tranquility#%E5%AE%89%E8%A3%85)，确保相关依赖被安装

**Comment by Lixiaojun-lab** [comment]
ok了哥，感谢您的指导！！！

**Comment by hooozen** [comment]
不用客气，有问题可以仔细阅读文档或者继续提 ISSUE，感谢支持。
