### ISSUE TITLE
打不开子页

### ISSUE THREAD

**Issue by great-xiang** [hooozen/hexo-theme-tranquility#3]
yml设置：
subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: me
      path: 
      title: 自我介绍
      icon: /images/icon/icon-sunrise.svg
      description: 自我介绍
    - name: tech
      path: 
      title: 技术
      icon: /images/icon/icon-book.svg
      description: 技术贴

git报错：

Unhandled rejection Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk)
  Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk) [Line 68, Column 55]
  Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk) [Line 1, Column 3]
  Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk) [Line 12, Column 41]
  Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk)
  Template render error: (C:\blog\blog\themes\xiang2\layout\_partials\components\post-nav.njk)
  Template render error: (C:\blog\blog\themes\xiang2\layout\post.njk)
  Template render error: (C:\blog\blog\themes\xiang2\layout\_partials\components\related-post.njk) [Line 4, Column 36]
  Error: Unable to call `popular_posts_json`, which is undefined or falsey
    at Object._prettifyError (C:\blog\blog\node_modules\nunjucks\src\lib.js:36:11)
    at C:\blog\blog\node_modules\nunjucks\src\environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\blog\blog\node_modules\nunjucks\src\environment.js:633:18), <anonymous>:35:3)
    at Template.render (C:\blog\blog\node_modules\nunjucks\src\environment.js:552:10)
    at C:\blog\blog\node_modules\hexo\lib\plugins\renderer\nunjucks.js:67:37
    at _View._compiled (C:\blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

debug两个小时解决不了，不想使用tranqulity了，想找个用的人多的，心累

**Comment by cjq0911** [comment]
我也是这有问题，太心累了

**Comment by hooozen** [comment]
不好意思，因为主题刚发布，可能很多使用场景文档里没有覆盖全面。关于你的这个问题，你有没有安装 hexo-related-popular-posts 插件呢？

**Comment by hooozen** [comment]
我重现了你的问题，请安装在项目根目录下 `hexo-related-popular-posts` 依赖：

`$ npm install hexo-related-popular-posts --save`

**Comment by great-xiang** [comment]
我试了一下，可以运行了，谢谢作者大大
