### ISSUE TITLE
关于网站运行错误.

### ISSUE THREAD

**Issue by geomuse** [hooozen/hexo-theme-tranquility#32]
不好意思 , 网站不能执行 . 

出现以下代码. 

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'enable')
    at Hexo.subpage_generator (C:\Users\boonh\Downloads\g\themes\tranquility\scripts\generator\subpage.js:42:33)
    at Hexo.tryCatcher (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\boonh\Downloads\g\node_modules\hexo\dist\hexo\index.js:333:28
    at tryCatcher (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\boonh\Downloads\g\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by hooozen** [comment]
这个错误是由于配置文件配置错误、缺少字段造成的，请仔细阅读使用说明[配置](https://github.com/hooozen/hexo-theme-tranquility?tab=readme-ov-file#%E9%85%8D%E7%BD%AE)，并参照[配置模版](https://github.com/hooozen/hexo-theme-test/blob/main/_config.tranquility.yml)
